import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import Toolbar from "@/components/toolbar"
import { Suspense } from "react";
import { deleteModel } from "@/lib/api/models";
import { redirect } from "next/navigation";
import { getCategories } from "@/lib/api/categories";

const nunitoSans = Nunito_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function handleDeleteModel(modelId: number) {
  "use server"
  if (modelId > 0)
    await deleteModel(modelId);
  redirect("/");
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cats = await getCategories();
  return (
    <html lang="en" className={nunitoSans.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider className="pt-2 pb-2 pr-2" defaultOpen={false}>
            <Suspense>
              <AppSideBar cats={cats} />
            </Suspense>
            <SidebarInset className="pb-2">
              <Suspense>
                <Toolbar handleDeleteModel={handleDeleteModel} />
              </Suspense>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
